"""Full seed data for IndiGuide categories and scenarios."""

def get_seed_data():
    return [
        {
            "slug": "transport",
            "name": "Transport & Taxis",
            "icon": "CarTaxiFront",
            "description": "Auto-rickshaws, cabs, ride apps",
            "image": "https://images.unsplash.com/photo-1763225398132-1e9985d9dacc?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
            "order": 1,
            "city": "delhi_ncr",
            "scenarios": [
                {"id": "transport-1", "title": "Driver quoting high price", "what_it_means": "Standard practice for auto-rickshaw drivers in Delhi to quote 2-3x the actual fare to foreigners.", "normalcy": "normal", "what_to_do": ["Ask 'Meter chalao'", "Check Google Maps distance", "Walk to the next auto"], "what_not_to_do": ["Don't get angry", "Don't pay first price", "Don't argue loudly"], "helpful_phrase": {"text": "Bhaiya, meter se chalenge", "pronunciation": "BHY-ya, MEE-ter say cha-LEN-gay", "meaning": "Brother, let's go by meter", "tone": "Polite but firm"}, "reassurance": "Every local negotiates too. You're not being singled out."},
                {"id": "transport-2", "title": "Driver refuses to use meter", "what_it_means": "Some drivers prefer fixed rates. Some are overcharging.", "normalcy": "sometimes_normal", "what_to_do": ["Insist on meter politely", "Use Uber/Ola as backup", "Agree on price before sitting"], "what_not_to_do": ["Don't sit before agreeing fare", "Don't threaten police"], "helpful_phrase": {"text": "Kitna lagega?", "pronunciation": "KIT-na la-GAY-ga", "meaning": "How much will it cost?", "tone": "Casual inquiry"}, "reassurance": "App-based rides are reliable in Delhi."},
                {"id": "transport-3", "title": "Driver asks to cancel app ride", "what_it_means": "Driver wants to avoid platform commission and charge directly.", "normalcy": "red_flag", "what_to_do": ["Politely decline", "Cancel and rebook if they insist", "Screenshot driver details"], "what_not_to_do": ["Don't cancel and pay cash", "Don't share personal number"], "helpful_phrase": {"text": "App se hi chalenge", "pronunciation": "APP say hee cha-LEN-gay", "meaning": "We'll go through the app only", "tone": "Firm but polite"}, "reassurance": "A new driver will accept in minutes."},
                {"id": "transport-4", "title": "Cannot find pickup zone", "what_it_means": "Delhi addresses use landmarks, not exact coordinates. GPS often inaccurate.", "normalcy": "normal", "what_to_do": ["Call driver via app", "Share nearby landmark", "Walk to main road"], "what_not_to_do": ["Don't wander into unknown streets", "Don't panic-cancel"], "helpful_phrase": {"text": "Main road pe hoon", "pronunciation": "MAIN road pay HOON", "meaning": "I'm on the main road", "tone": "Simple location info"}, "reassurance": "Pickup confusion is universal in Delhi."},
                {"id": "transport-5", "title": "Driver taking a different route", "what_it_means": "Usually traffic avoidance. Delhi has severe congestion.", "normalcy": "sometimes_normal", "what_to_do": ["Check Google Maps", "If ETA similar, it's fine", "Calmly point out if clearly wrong"], "what_not_to_do": ["Don't immediately accuse", "Don't exit in unfamiliar area"], "helpful_phrase": {"text": "Google Maps kya dikha raha hai?", "pronunciation": "GOOGLE MAPS kya dik-HA ra-HA hai", "meaning": "What is Google Maps showing?", "tone": "Non-confrontational"}, "reassurance": "Most route changes are genuine traffic workarounds."}
            ]
        },
        {
            "slug": "markets",
            "name": "Markets & Bargaining",
            "icon": "ShoppingBag",
            "description": "Negotiating, vendors, shopping",
            "image": "https://images.unsplash.com/photo-1717065165653-bb853b7e6e7e?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
            "order": 2,
            "city": "delhi_ncr",
            "scenarios": [
                {"id": "markets-1", "title": "Vendor quotes absurdly high price", "what_it_means": "First price for tourists is 3-10x actual value. Opening of negotiation.", "normalcy": "normal", "what_to_do": ["Counter with 20-30% of quoted price", "Compare at 2-3 stalls", "Walk away — they'll call you back"], "what_not_to_do": ["Don't pay first price", "Don't show excitement", "Don't feel guilty bargaining"], "helpful_phrase": {"text": "Bahut zyada hai, thoda kam karo", "pronunciation": "BA-hut ZYA-da hai, THO-da KUM ka-RO", "meaning": "Too expensive, reduce a bit", "tone": "Standard bargaining"}, "reassurance": "Bargaining is expected and enjoyed."},
                {"id": "markets-2", "title": "Vendor follows you persistently", "what_it_means": "Aggressive selling common in tourist markets.", "normalcy": "sometimes_normal", "what_to_do": ["Say 'Nahi chahiye' firmly", "Avoid eye contact", "Enter a different shop"], "what_not_to_do": ["Don't be rude", "Don't enter their shop 'just to look'"], "helpful_phrase": {"text": "Nahi chahiye, shukriya", "pronunciation": "NA-hee CHA-hi-yay, SHUK-ri-ya", "meaning": "Don't need it, thanks", "tone": "Polite but final"}, "reassurance": "Standard market behavior. You're doing nothing wrong by saying no."},
                {"id": "markets-3", "title": "Vendor claims 'fixed price'", "what_it_means": "There is no government rate for souvenirs. Pressure tactic.", "normalcy": "red_flag", "what_to_do": ["Ignore the claim", "Counter-offer anyway", "Leave if they won't negotiate"], "what_not_to_do": ["Don't believe fixed price claims", "Don't fall for 'special discount'"], "helpful_phrase": {"text": "Dusri dukaan mein sasta hai", "pronunciation": "DOO-sri du-KAAN mein SAS-ta hai", "meaning": "It's cheaper at the other shop", "tone": "Creates competitive pressure"}, "reassurance": "No tourist market in Delhi has fixed prices."},
                {"id": "markets-4", "title": "Multiple vendors crowd around you", "what_it_means": "Vendors competing for attention. Overwhelming but rarely threatening.", "normalcy": "sometimes_normal", "what_to_do": ["Pick one vendor", "Tell others 'Baad mein'", "Move to less crowded section"], "what_not_to_do": ["Don't panic", "Don't pull out cash in crowd"], "helpful_phrase": {"text": "Ek minute, pehle dekh lene do", "pronunciation": "EK mi-NUT, PEH-lay dekh LAY-nay do", "meaning": "One minute, let me look first", "tone": "Buys you space"}, "reassurance": "This energy is part of Indian market culture. You're safe."},
                {"id": "markets-5", "title": "Vendor gets angry when you walk away", "what_it_means": "Almost always a negotiation tactic. Feigned offense.", "normalcy": "normal", "what_to_do": ["Keep walking", "Return casually later if interested", "Know this is theater"], "what_not_to_do": ["Don't feel guilty", "Don't rush back", "Don't overpay to avoid confrontation"], "helpful_phrase": {"text": "", "pronunciation": "", "meaning": "Silence and walking away IS the phrase", "tone": "No words needed"}, "reassurance": "Nobody is truly angry. In 30 seconds they'll be smiling at the next customer."}
            ]
        },
        {
            "slug": "food",
            "name": "Restaurants & Food",
            "icon": "Utensils",
            "description": "Ordering, spice levels, hygiene",
            "image": "https://images.unsplash.com/photo-1680993032090-1ef7ea9b51e5?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
            "order": 3,
            "city": "delhi_ncr",
            "scenarios": [
                {"id": "food-1", "title": "Menu has no English", "what_it_means": "Many local restaurants only have Hindi menus. Best food is often here.", "normalcy": "normal", "what_to_do": ["Ask 'Kya special hai?'", "Point at what others eat", "Use Google Lens", "Safe starters: Paneer butter masala, Dal makhani"], "what_not_to_do": ["Don't leave because of language", "Don't order blindly"], "helpful_phrase": {"text": "Kam mirchi mein banana", "pronunciation": "KUM mir-CHEE mein ba-NA-na", "meaning": "Make it with less chili", "tone": "Important request"}, "reassurance": "Hindi-only menus usually mean incredible, authentic food."},
                {"id": "food-2", "title": "Waiter keeps pushing expensive items", "what_it_means": "Some push higher-margin items. Sometimes genuinely recommending.", "normalcy": "sometimes_normal", "what_to_do": ["Ask for 'sabse popular' dish", "Check prices first", "Order one dish, add more later"], "what_not_to_do": ["Don't order everything suggested", "Don't skip asking portion sizes"], "helpful_phrase": {"text": "Log kya order karte hain?", "pronunciation": "LOG kya OR-der KAR-tay hain", "meaning": "What do people usually order?", "tone": "Redirects to popular choices"}, "reassurance": "Delhi food is incredibly good value."},
                {"id": "food-3", "title": "Food is extremely spicy", "what_it_means": "Delhi cuisine is genuinely spicy. Not trying to prank you.", "normalcy": "normal", "what_to_do": ["Eat curd or drink lassi — NOT water", "Ask for raita", "Next time say 'Bilkul kam mirchi'"], "what_not_to_do": ["Don't drink water rapidly", "Don't complain angrily"], "helpful_phrase": {"text": "Dahi de dijiye", "pronunciation": "DA-hee day DEE-ji-yay", "meaning": "Please give me yogurt", "tone": "Instant relief"}, "reassurance": "Your tongue adjusts in a few days. Yogurt is your friend."},
                {"id": "food-4", "title": "Bill has unexpected charges", "what_it_means": "Service charge (5-10%) and GST are common.", "normalcy": "sometimes_normal", "what_to_do": ["Ask for itemized bill", "Service charge is legally optional", "GST is mandatory"], "what_not_to_do": ["Don't pay without checking", "Don't tip on top of service charge"], "helpful_phrase": {"text": "Bill detail mein dikhayiye", "pronunciation": "BILL dee-TAIL mein dik-HA-ee-yay", "meaning": "Show me the detailed bill", "tone": "Calm request"}, "reassurance": "Most charges are legitimate. You have the right to question them."},
                {"id": "food-5", "title": "Street food hygiene concerns", "what_it_means": "Busy stalls with high turnover are generally safe.", "normalcy": "normal", "what_to_do": ["Choose stalls with long local queues", "Stick to freshly cooked hot items", "Carry hand sanitizer"], "what_not_to_do": ["Don't avoid street food entirely", "Don't drink tap water", "Don't eat from empty stalls"], "helpful_phrase": {"text": "Taza hai?", "pronunciation": "TA-za hai", "meaning": "Is it fresh?", "tone": "Shows awareness"}, "reassurance": "Delhi's street food has fed millions safely for generations."}
            ]
        },
        {
            "slug": "trains",
            "name": "Train Stations & Buses",
            "icon": "TrainFront",
            "description": "Platforms, porters, tickets",
            "image": "https://images.pexels.com/photos/2526935/pexels-photo-2526935.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
            "order": 4,
            "city": "delhi_ncr",
            "scenarios": [
                {"id": "trains-1", "title": "Someone claims your reserved seat", "what_it_means": "Overcrowded trains lead to seat disputes.", "normalcy": "sometimes_normal", "what_to_do": ["Show your ticket", "Check reservation chart on coach", "Ask TTE to resolve"], "what_not_to_do": ["Don't give up seat without checking", "Don't argue loudly"], "helpful_phrase": {"text": "Yeh meri seat hai, ticket dekh lijiye", "pronunciation": "YEH meh-REE SEAT hai, TI-ket dekh LEE-ji-yay", "meaning": "This is my seat, please check the ticket", "tone": "Firm and factual"}, "reassurance": "Reserved means reserved. The TTE will sort it out."},
                {"id": "trains-2", "title": "Porter grabs your luggage", "what_it_means": "Licensed porters in red shirts. Aggressive approach, not theft.", "normalcy": "normal", "what_to_do": ["Hold bag firmly if not needed", "Agree on price first — Rs 50-100/bag", "Check official rate charts"], "what_not_to_do": ["Don't panic or accuse", "Don't pay without agreement"], "helpful_phrase": {"text": "Kitna loge?", "pronunciation": "KIT-na LO-gay", "meaning": "How much will you charge?", "tone": "Negotiate before service"}, "reassurance": "Red-shirted porters are licensed. Agree on price first."},
                {"id": "trains-3", "title": "Official-looking person demands documents", "what_it_means": "Real TTEs wear uniforms with photo IDs. Others may be scammers.", "normalcy": "red_flag", "what_to_do": ["Ask for official ID", "Only show ticket, not passport", "Walk to Station Master if unsure"], "what_not_to_do": ["Don't hand over passport", "Don't pay cash fines on spot"], "helpful_phrase": {"text": "Aapka ID dikhayiye", "pronunciation": "AAP-ka ID dik-HA-ee-yay", "meaning": "Show me your ID", "tone": "Perfectly acceptable"}, "reassurance": "Real officials never demand cash without receipts."},
                {"id": "trains-4", "title": "Platform change in Hindi only", "what_it_means": "Announcements are Hindi first, English second.", "normalcy": "normal", "what_to_do": ["Check electronic display boards", "Ask fellow passengers", "Use IRCTC app", "Arrive 30 min early"], "what_not_to_do": ["Don't rush without confirming", "Don't rely on announcements alone"], "helpful_phrase": {"text": "Train kaunse platform pe hai?", "pronunciation": "TRAIN kaun-SAY PLAT-form pay hai", "meaning": "Which platform is the train on?", "tone": "Anyone will help"}, "reassurance": "Indians are extremely helpful at train stations."},
                {"id": "trains-5", "title": "Someone offers to help buy tickets", "what_it_means": "Touts sell fake tickets or redirect to agencies.", "normalcy": "red_flag", "what_to_do": ["Decline and go to official counter", "Use IRCTC app", "Find Tourist Quota counter"], "what_not_to_do": ["Don't give money to strangers", "Don't follow them away from station"], "helpful_phrase": {"text": "Main khud le lunga", "pronunciation": "MAIN KHUD lay LOON-ga", "meaning": "I'll get it myself", "tone": "Simple refusal"}, "reassurance": "Every major station has proper counters and tourist help."}
            ]
        },
        {
            "slug": "social",
            "name": "Social Interactions",
            "icon": "Users",
            "description": "Strangers, conversations, boundaries",
            "image": "https://images.pexels.com/photos/35160627/pexels-photo-35160627.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
            "order": 5,
            "city": "delhi_ncr",
            "scenarios": [
                {"id": "social-1", "title": "Someone asks for a selfie", "what_it_means": "Genuine excitement to meet foreigners. Not a threat.", "normalcy": "normal", "what_to_do": ["Smile and take photo if comfortable", "Decline politely if not", "Walk away if too many requests"], "what_not_to_do": ["Don't feel obligated", "Don't get angry"], "helpful_phrase": {"text": "Aaj nahi, shukriya", "pronunciation": "AAJ na-HEE, SHUK-ri-ya", "meaning": "Not today, thanks", "tone": "Friendly decline"}, "reassurance": "One of India's most wholesome interactions."},
                {"id": "social-2", "title": "Person offers to be your guide", "what_it_means": "Could be genuine or commission-based.", "normalcy": "sometimes_normal", "what_to_do": ["Thank and decline", "Negotiate fee upfront if interested", "Never follow to specific shops"], "what_not_to_do": ["Don't follow strangers", "Don't share hotel name"], "helpful_phrase": {"text": "Main apne aap ghoom raha hoon", "pronunciation": "MAIN AP-nay AAP ghoom RA-ha hoon", "meaning": "I'm exploring on my own", "tone": "Clear boundary"}, "reassurance": "A clear 'no thanks' is always respected."},
                {"id": "social-3", "title": "Group of men staring at you", "what_it_means": "Staring is culturally common. Usually curiosity, not aggression.", "normalcy": "sometimes_normal", "what_to_do": ["Confident nod can break the stare", "Move to crowded area if uncomfortable", "Enter a shop or restaurant", "Call 112 if threatening"], "what_not_to_do": ["Don't stare back aggressively", "Don't confront", "Don't isolate yourself"], "helpful_phrase": {"text": "", "pronunciation": "", "meaning": "Confident body language is more effective than words", "tone": "Walk with purpose"}, "reassurance": "Staring is the #1 culture shock. It's usually harmless curiosity."},
                {"id": "social-4", "title": "Stranger asks very personal questions", "what_it_means": "Standard friendly conversation in India. Not rude.", "normalcy": "normal", "what_to_do": ["Answer what you're comfortable with", "Give vague answers for sensitive topics", "Redirect with 'Aap batao'"], "what_not_to_do": ["Don't take offense", "Don't share financials", "Don't reveal hotel address"], "helpful_phrase": {"text": "Aap batao", "pronunciation": "AAP ba-TAO", "meaning": "You tell me / What about you?", "tone": "Deflects warmly"}, "reassurance": "Indians ask each other these same questions daily."},
                {"id": "social-5", "title": "Child approaches asking for money", "what_it_means": "Organized begging exists. Children may be controlled by adults.", "normalcy": "sometimes_normal", "what_to_do": ["Don't give cash directly", "Buy them food instead", "Donate to NGOs like CRY or Pratham"], "what_not_to_do": ["Don't give money", "Don't take photos", "Don't ignore the emotional impact"], "helpful_phrase": {"text": "Khana khayega?", "pronunciation": "KHA-na KHA-yay-ga", "meaning": "Will you eat food?", "tone": "Offering food is better"}, "reassurance": "Food or NGO donations make a real, lasting difference."}
            ]
        },
        {
            "slug": "safety",
            "name": "Safety Uncertainty",
            "icon": "ShieldAlert",
            "description": "Feeling unsafe, scams, emergencies",
            "image": "https://images.unsplash.com/photo-1768141715823-7dceae5cf421?crop=entropy&cs=srgb&fm=jpg&q=85&w=800",
            "order": 6,
            "city": "delhi_ncr",
            "scenarios": [
                {"id": "safety-1", "title": "Area feels unsafe at night", "what_it_means": "Delhi safety varies by area and time.", "normalcy": "sometimes_normal", "what_to_do": ["Move to well-lit main roads", "Book Uber/Ola immediately", "Share live location", "Metro closes at 11 PM"], "what_not_to_do": ["Don't walk alone after dark", "Don't wear earphones", "Don't take shortcuts"], "helpful_phrase": {"text": "", "pronunciation": "", "meaning": "Open Uber/Ola and get a ride", "tone": "Action over words"}, "reassurance": "Delhi's main areas are well-patrolled. Getting a ride is smart."},
                {"id": "safety-2", "title": "Being followed by someone", "what_it_means": "Not normal. Take it seriously.", "normalcy": "red_flag", "what_to_do": ["Enter nearest shop or hotel lobby", "Call 112 emergency number", "Make noise to draw attention", "Share live location"], "what_not_to_do": ["Don't go to your hotel", "Don't confront alone", "Don't run into empty streets"], "helpful_phrase": {"text": "Police!", "pronunciation": "po-LEES", "meaning": "Everyone understands this", "tone": "Shout if threatened"}, "reassurance": "Enter a public place and call 112. You're doing the right thing."},
                {"id": "safety-3", "title": "Scam attempt suspected", "what_it_means": "Common scams: closed sites, gem trade, fake agents, shoe cleaning.", "normalcy": "sometimes_normal", "what_to_do": ["Say 'Nahi' and walk away", "Verify claims independently", "Never follow to 'special place'", "Check sites yourself"], "what_not_to_do": ["Don't engage with stories", "Don't give passport to strangers", "Don't feel rude walking away"], "helpful_phrase": {"text": "Nahi chahiye, shukriya", "pronunciation": "NA-hee CHA-hi-yay, SHUK-ri-ya", "meaning": "Don't need it, thanks", "tone": "Firm, final"}, "reassurance": "Recognizing a scam is the hard part — you've already done it."},
                {"id": "safety-4", "title": "Lost and phone battery low", "what_it_means": "Stressful but very solvable in Delhi.", "normalcy": "sometimes_normal", "what_to_do": ["Find shop to charge phone (Rs 20-50)", "Ask for nearest Metro station", "Look for police PCR vans", "Tourist Helpline: 1800-111-363"], "what_not_to_do": ["Don't panic visibly", "Don't follow strangers", "Don't drain battery on social media"], "helpful_phrase": {"text": "Nearest metro station kahan hai?", "pronunciation": "NEAR-est MET-ro STA-tion ka-HAN hai", "meaning": "Where's the nearest metro station?", "tone": "Everyone knows the answer"}, "reassurance": "Every shop has a charger. Every person knows the nearest Metro."},
                {"id": "safety-5", "title": "Aggressive street dogs", "what_it_means": "Stray dogs are common. Territorial at night.", "normalcy": "normal", "what_to_do": ["Walk slowly, don't run", "Avoid eye contact", "Pretend to pick up a stone", "Hospital immediately if bitten"], "what_not_to_do": ["Don't run", "Don't try to pet strays", "Don't corner them"], "helpful_phrase": {"text": "Hatao!", "pronunciation": "ha-TAO", "meaning": "Go away! / Shoo!", "tone": "Loud and commanding"}, "reassurance": "Most strays are docile. The stone-picking gesture is your best tool."}
            ]
        },
        {
            "slug": "temples",
            "name": "Temples & Etiquette",
            "icon": "Landmark",
            "description": "Religious sites, customs, respect",
            "image": "https://images.pexels.com/photos/10678945/pexels-photo-10678945.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
            "order": 7,
            "city": "delhi_ncr",
            "scenarios": [
                {"id": "temples-1", "title": "Asked to remove shoes", "what_it_means": "Required at all temples, mosques, gurudwaras. Non-negotiable.", "normalcy": "normal", "what_to_do": ["Remove shoes at designated area", "Use shoe counter (Rs 10-20)", "Carry socks for hot floors"], "what_not_to_do": ["Don't refuse", "Don't walk in with shoes", "Don't complain about floors"], "helpful_phrase": {"text": "Joote kahan rakhoon?", "pronunciation": "JOO-tay ka-HAN ra-KHOON", "meaning": "Where should I keep my shoes?", "tone": "Practical, shows awareness"}, "reassurance": "Everyone does this. Your shoes are safe at the counter."},
                {"id": "temples-2", "title": "Someone offers 'blessing' for money", "what_it_means": "Self-appointed 'priests' outside temples demand payment.", "normalcy": "red_flag", "what_to_do": ["Decline BEFORE they start", "Keep hands at your sides", "You owe nothing if they already started", "Head to official entrance"], "what_not_to_do": ["Don't extend hands", "Don't let them tie anything", "Don't pay"], "helpful_phrase": {"text": "Main andar ja raha hoon", "pronunciation": "MAIN AN-dar ja RA-ha hoon", "meaning": "I'm going inside", "tone": "Moves past them"}, "reassurance": "Real blessings inside temples are always free."},
                {"id": "temples-3", "title": "Unsure about taking photos", "what_it_means": "Rules vary. Main sanctum usually no-photo.", "normalcy": "sometimes_normal", "what_to_do": ["Look for signs at entrance", "Ask volunteer before shooting", "Never photograph main deity without permission"], "what_not_to_do": ["Don't use flash", "Don't photograph people praying", "Don't take selfies in prayer areas"], "helpful_phrase": {"text": "Photo le sakte hain?", "pronunciation": "PHO-to lay SAK-tay hain", "meaning": "Can we take photos?", "tone": "Ask first — people appreciate it"}, "reassurance": "Most outer areas are photo-friendly. Just ask near sacred spaces."},
                {"id": "temples-4", "title": "Accidentally touched something sacred", "what_it_means": "Some items are sacred. Feet shouldn't point at sacred objects.", "normalcy": "sometimes_normal", "what_to_do": ["Use right hand for offerings", "Sit cross-legged, not legs extended", "Simple apology is always enough", "Watch and mirror locals"], "what_not_to_do": ["Don't touch idols", "Don't point feet at shrines", "Don't sit with back to deity"], "helpful_phrase": {"text": "Maaf kijiye", "pronunciation": "MAAF kee-JI-yay", "meaning": "Please forgive me", "tone": "Sincere — always accepted"}, "reassurance": "A genuine apology is always accepted warmly."},
                {"id": "temples-5", "title": "Being pressured for donations", "what_it_means": "Temples accept voluntary donations. Some individuals pressure.", "normalcy": "normal", "what_to_do": ["Donate only in official boxes", "Rs 10-100 is fine", "Decline persistent individuals", "Try gurudwara langar (free meal)"], "what_not_to_do": ["Don't feel pressured for large amounts", "Don't give to 'special prayer' claims"], "helpful_phrase": {"text": "Daan peti kahan hai?", "pronunciation": "DAAN PAY-tee ka-HAN hai", "meaning": "Where is the donation box?", "tone": "Proper channels"}, "reassurance": "Any amount is respected. Your presence matters more than money."}
            ]
        }
    ]
